services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - POSTS_DIR=/posts
    expose:
      - "5000"
    volumes:
      - ./apps/frontend/blog_bm0p/src/content/posts:/posts
    # (선택) 코드 변경 시 자동 반영하려면:
    # volumes:
    #   - ./apps/backend:/app
  frontend:
    build:
      context: ./apps/frontend/blog_bm0p
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=4321
    expose:
      - "4321"
    volumes:
      - ./apps/frontend/blog_bm0p/src/content/posts:/app/src/content/posts

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
  # 호스트의 설정 파일을 컨테이너에 읽기 전용으로 연결
    volumes:
      - ./nginx/conf/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
